### PR TITLE
Added null support to templates

### PR DESCRIPTION
**Pull request by Pchelolo**
Need an ability to specify nulls in templates.

cc @wikimedia/services

### CODE REVIEW

**Comment by d00rman** [comment]
:+1: Can we get this ASAP? We need it for change-prop for https://gerrit.wikimedia.org/r/#/c/292366/

**Comment by Pchelolo** [comment]
we need @gwicke

**Comment by d00rman** [comment]
> we need @gwicke

Yup. On that note, it might be worth transferring this repo over to the org.

**Comment by d00rman** [comment]
Published as [v0.1.9](https://github.com/wikimedia/template-expression-compiler/tree/v0.1.9)

**Pull request merged**
